msg-prefix:
  - "[元界](color=#39C5BB bold hover=初音未来绿 &8/ &7#39C5BB) &f&l>>> "
  - "[元界](color=#FFA500 bold hover=镜音铃橙黄 &8/ &7#FFA500) &f&l>>> "
  - "[元界](color=#FC8BAB bold hover=哔哩哔哩粉 &8/ &7#FC8BAB) &f&l>>> "
  - "[元界](color=#F0A1A8 bold hover=中国色·合欢红 &8/ &7#F0A1A8) &f&l>>> "
  - "[元界](color=#51C4D3 bold hover=中国色·瀑布蓝 &8/ &7#51C4D3) &f&l>>> "
  - "[元界](color=#2bae85 bold hover=中国色·铜绿 &8/ &7#2bae85) &f&l>>> "
  - "[元界](color=#2bae85 bold hover=中国色·铜绿 &8/ &7#2bae85) &f&l>>> "
  - "[元界](color=#eb3c70 bold hover=中国色·松叶牡丹红 &8/ &7#eb3c70) &f&l>>> "
  - "[元界](color=#6768AB bold hover=彩通·2022年代表色-长春花蓝 &8/ &7#6768AB) &f&l>>> "
  - "[元界](color=#6768AB bold hover=彩通·2022年代表色-长春花蓝 &8/ &7#6768AB) &f&l>>> "
  - "[元界](color=#002FA7 bold hover=克莱因蓝 &8/ &7#002FA7) &f&l>>> "

database:
